let peliculas = [
    pand=      {    titulo :    "Pandemia Fight Club",
                    autor :     "Santi Sosa", 
                    ano :       2021, 
                    img :       "img/pand.png",
                    link:       "https://www.youtube.com/watch?v=wC38kcMX-oI",
                    tipo :      "cortometraje"
                },
    caracol=    {   titulo :    "Caracol Baboso",
                    autor :     "Max Bridas", 
                    ano :       2021, 
                    img :       "img/caracol.png", 
                    link:       "https://www.youtube.com/watch?v=iqBE3jHgxn8",
                    tipo :      "videoclip"
                },
    culpa=      {   titulo :    "No es mi culpa",
                    autor :     "Santi Sosa", 
                    ano :       2020, 
                    img :       "img/culpa.png", 
                    link:       "https://www.youtube.com/watch?v=qzomzh-csi8",
                    tipo :      "cortometraje"
                },
    covid=      {   titulo :    "covid XXI",
                    autor :     "Max Bridas", 
                    ano :       2021, 
                    img :       "img/covid.png", 
                    link:       "https://www.youtube.com/watch?v=z-PvvpzRJVk",
                    tipo :      "cortometraje"
                },
    vida=       {   titulo :    "La vida Empieza",
                    autor :     "Santi Sosa", 
                    ano :       2021, 
                    img :       "img/vida.png", 
                    link:       "https://www.youtube.com/watch?v=qu57I7y1kPM",
                    tipo :      "cortometraje"
                },
    huracan=    {   titulo :    "huracán",
                    autor :     "Max Bridas", 
                    ano :       2019, 
                    img :       "img/huracan.png", 
                    link:       "https://www.youtube.com/watch?v=MVI7obxySm4",
                    tipo :      "videoclip"
                },
    bikini=     {   titulo :    "Operacion Bikini",
                    autor :     "Santi Sosa", 
                    ano :       2018, 
                    img :       "img/bikini.png", 
                    link:       "https://www.youtube.com/watch?v=eMtkCXQVHeY",
                    tipo :      "cortometraje"
                },
    mk=         {   titulo :    "MKam Ultra",
                    autor :     "Max Bridas", 
                    ano :       2016, 
                    img :       "img/mk.png", 
                    link:       "https://www.youtube.com/watch?v=72hYbu2hIaY",
                    tipo :      "cortometraje"
                },
    selfie=     {   titulo :    "Selfie Killer",
                    autor :     "Max Bridas", 
                    ano :       2021, 
                    img :       "img/selfie.png",
                    link:       "https://www.youtube.com/watch?v=sA7Cq4LuZeM", 
                    tipo :      "cortometraje"
                }
            ]
